const fs = require("fs");
const path = require("path");
const base = "miniprogram";

function write(file, content) {
  const p = path.join(base, file);
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, content, "utf8");
}

write("app.wxss", "page { background: #f5f5f5; } .container { padding: 20px; } .card { background: #fff; border-radius: 8px; padding: 16px; margin-bottom: 12px; } .title { font-size: 18px; font-weight: bold; margin-bottom: 8px; } .label { color: #666; font-size: 14px; } .value { color: #333; font-size: 14px; } .btn { margin-top: 12px; }");
write("sitemap.json", JSON.stringify({ desc: "术后随访小程序", rules: [{ action: "allow", page: "*" }] }));

write("pages/login/login.wxml", '<view class="container">\n  <view class="title">术后随访小程序</view>\n  <radio-group bindchange="onRoleChange">\n    <label><radio value="patient" checked="true" />患者</label>\n    <label><radio value="doctor" />医生</label>\n    <label><radio value="nurse" />护士</label>\n    <label><radio value="admin" />管理员</label>\n  </radio-group>\n  <button type="primary" bindtap="login">微信登录（模拟）</button>\n</view>');

write("pages/patient-home/patient-home.js", 'const api = require("../../utils/api");\nPage({\n  data: { patient: null, tasks: [] },\n  async onShow() {\n    try {\n      const me = await api.getMe();\n      if (me.user.role !== "patient") return;\n      const tasks = await api.getMyTasks();\n      this.setData({ tasks: tasks.list });\n    } catch(e) { console.error(e); }\n  },\n  goSurgery() { wx.navigateTo({ url: "/pages/patient-surgery/patient-surgery" }); },\n  goFollowup() { wx.navigateTo({ url: "/pages/patient-followup/patient-followup" }); },\n});');
write("pages/patient-home/patient-home.wxml", '<view class="container">\n  <view class="card">\n    <view class="title">我的复诊提醒</view>\n    <view wx:for="{{tasks}}" wx:key="id" class="card">\n      <view>{{item.title}}</view>\n      <view class="label">截止日期: {{item.dueDate}}</view>\n      <view class="label" wx:if="{{item.status===\'overdue\'}}" style="color:red">已逾期</view>\n    </view>\n    <view wx:if="{{tasks.length===0}}" class="label">暂无待处理提醒</view>\n  </view>\n  <button class="btn" bindtap="goSurgery">我的手术</button>\n  <button class="btn" bindtap="goFollowup">复诊提醒</button>\n</view>');

write("pages/patient-surgery/patient-surgery.js", 'const api = require("../../utils/api");\nPage({\n  data: { surgeries: [] },\n  async onLoad() {\n    try {\n      const me = await api.getMe();\n      if (!me.user.patients || !me.user.patients.length) return;\n      const res = await api.getSurgeries(me.user.patients[0].id);\n      this.setData({ surgeries: res.list });\n    } catch(e) { console.error(e); }\n  },\n});');
write("pages/patient-surgery/patient-surgery.wxml", '<view class="container">\n  <view class="title">我的手术</view>\n  <view wx:for="{{surgeries}}" wx:key="id" class="card">\n    <view>{{item.surgeryName}}</view>\n    <view class="label">科室: {{item.department.name}}</view>\n    <view class="label">手术时间: {{item.surgeryTime}}</view>\n  </view>\n</view>');

write("pages/patient-followup/patient-followup.js", 'const api = require("../../utils/api");\nPage({\n  data: { tasks: [] },\n  async onLoad() {\n    try {\n      const res = await api.getMyTasks();\n      this.setData({ tasks: res.list });\n    } catch(e) { console.error(e); }\n  },\n  async fillRecord(e) {\n    const id = e.currentTarget.dataset.id;\n    try {\n      await api.submitRecord(id, { content: "患者已填写" });\n      wx.showToast({ title: "提交成功" });\n      const res = await api.getMyTasks();\n      this.setData({ tasks: res.list });\n    } catch(e) { wx.showToast({ title: "提交失败", icon: "none" }); }\n  },\n});');
write("pages/patient-followup/patient-followup.wxml", '<view class="container">\n  <view class="title">复诊提醒</view>\n  <view wx:for="{{tasks}}" wx:key="id" class="card">\n    <view>{{item.title}}</view>\n    <view class="label">截止日期: {{item.dueDate}}</view>\n    <view class="label" style="color:{{item.status===\'overdue\'?\'red\':\'#666\'}}">状态: {{item.status}}</view>\n    <button wx:if="{{item.status===\'pending\' || item.status===\'overdue\'}}" data-id="{{item.id}}" bindtap="fillRecord" size="mini" type="primary">填写记录</button>\n  </view>\n</view>');

write("pages/patient-mine/patient-mine.js", 'const api = require("../../utils/api");\nPage({\n  data: { user: null },\n  async onShow() {\n    try {\n      const res = await api.getMe();\n      this.setData({ user: res.user });\n    } catch(e) { console.error(e); }\n  },\n  async bindPhone() {\n    const phone = "13900000001";\n    try {\n      await api.bindPhone({ phone });\n      wx.showToast({ title: "绑定成功" });\n      const res = await api.getMe();\n      this.setData({ user: res.user });\n    } catch(e) { wx.showToast({ title: "绑定失败", icon: "none" }); }\n  },\n  logout() {\n    wx.removeStorageSync("token");\n    getApp().globalData.token = null;\n    wx.redirectTo({ url: "/pages/login/login" });\n  },\n});');
write("pages/patient-mine/patient-mine.wxml", '<view class="container">\n  <view class="card">\n    <view class="title">我的</view>\n    <view class="label">角色: {{user.role}}</view>\n    <view class="label">手机号: {{user.phone || \'未绑定\'}}</view>\n    <button wx:if="{{!user.phone}}" bindtap="bindPhone" size="mini" type="primary">绑定手机号</button>\n  </view>\n  <button class="btn" bindtap="logout">退出登录</button>\n</view>');

write("pages/staff-workbench/staff-workbench.js", 'const api = require("../../utils/api");\nPage({\n  data: { stats: {} },\n  async onShow() {\n    try {\n      const res = await api.getDashboard();\n      this.setData({ stats: res });\n    } catch(e) { console.error(e); }\n  },\n  goPatients() { wx.navigateTo({ url: "/pages/staff-patients/staff-patients" }); },\n  goTasks() { wx.navigateTo({ url: "/pages/staff-followup-tasks/staff-followup-tasks" }); },\n});');
write("pages/staff-workbench/staff-workbench.wxml", '<view class="container">\n  <view class="title">工作台</view>\n  <view class="card">\n    <view class="label">今日待随访: {{stats.todayPending}}</view>\n    <view class="label">今日已完成: {{stats.todayDone}}</view>\n    <view class="label" style="color:red">逾期未完成: {{stats.overdue}}</view>\n    <view class="label">我的患者: {{stats.myPatients}}</view>\n  </view>\n  <button class="btn" bindtap="goPatients">患者管理</button>\n  <button class="btn" bindtap="goTasks">随访任务</button>\n</view>');

write("pages/staff-patients/staff-patients.js", 'const api = require("../../utils/api");\nPage({\n  data: { patients: [], q: "" },\n  async onLoad() { this.load(); },\n  async load() {\n    try {\n      const res = await api.getPatients({ q: this.data.q });\n      this.setData({ patients: res.list });\n    } catch(e) { console.error(e); }\n  },\n  onSearch(e) {\n    this.setData({ q: e.detail.value });\n    this.load();\n  },\n  goDetail(e) {\n    const id = e.currentTarget.dataset.id;\n    wx.navigateTo({ url: "/pages/staff-patient-detail/staff-patient-detail?id=" + id });\n  },\n  goAdd() {\n    wx.navigateTo({ url: "/pages/staff-surgery-add/staff-surgery-add" });\n  },\n});');
write("pages/staff-patients/staff-patients.wxml", '<view class="container">\n  <view class="title">患者管理</view>\n  <input placeholder="搜索姓名/手机号" bindconfirm="onSearch" />\n  <button class="btn" bindtap="goAdd" type="primary" size="mini">新增患者/手术</button>\n  <view wx:for="{{patients}}" wx:key="id" class="card" bindtap="goDetail" data-id="{{item.id}}">\n    <view>{{item.name}}</view>\n    <view class="label">{{item.phone}}</view>\n    <view class="label" wx:if="{{item.surgeries.length}}">{{item.surgeries[0].surgeryName}}</view>\n  </view>\n</view>');

write("pages/staff-patient-detail/staff-patient-detail.js", 'const api = require("../../utils/api");\nPage({\n  data: { patient: null },\n  async onLoad(options) {\n    try {\n      const res = await api.getPatient(options.id);\n      this.setData({ patient: res.patient });\n    } catch(e) { console.error(e); }\n  },\n});');
write("pages/staff-patient-detail/staff-patient-detail.wxml", '<view class="container" wx:if="{{patient}}">\n  <view class="title">{{patient.name}}</view>\n  <view class="card">\n    <view class="label">性别: {{patient.gender}}</view>\n    <view class="label">手机号: {{patient.phone}}</view>\n    <view class="label">身份证号后四位: {{patient.idCardSuffix}}</view>\n  </view>\n  <view class="title">手术记录</view>\n  <view wx:for="{{patient.surgeries}}" wx:key="id" class="card">\n    <view>{{item.surgeryName}}</view>\n    <view class="label">手术时间: {{item.surgeryTime}}</view>\n  </view>\n  <view class="title">随访任务</view>\n  <view wx:for="{{patient.followupTasks}}" wx:key="id" class="card">\n    <view>{{item.title}}</view>\n    <view class="label">截止日期: {{item.dueDate}}</view>\n    <view class="label">状态: {{item.status}}</view>\n  </view>\n</view>');

write("pages/staff-surgery-add/staff-surgery-add.js", 'const api = require("../../utils/api");\nPage({\n  data: { name: "", phone: "", surgeryName: "", surgeryTime: "" },\n  async submit() {\n    try {\n      const p = await api.createPatient({ name: this.data.name, phone: this.data.phone });\n      await api.createSurgery({\n        patientId: p.patient.id,\n        surgeryName: this.data.surgeryName,\n        surgeryTime: new Date(this.data.surgeryTime).toISOString(),\n      });\n      wx.showToast({ title: "提交成功" });\n      wx.navigateBack();\n    } catch(e) {\n      wx.showToast({ title: "提交失败", icon: "none" });\n      console.error(e);\n    }\n  },\n});');
write("pages/staff-surgery-add/staff-surgery-add.wxml", '<view class="container">\n  <view class="title">新增患者与手术</view>\n  <view class="card">\n    <view class="label">患者姓名</view>\n    <input model:value="{{name}}" placeholder="请输入姓名" />\n    <view class="label">手机号</view>\n    <input model:value="{{phone}}" placeholder="请输入手机号" />\n    <view class="label">手术名称</view>\n    <input model:value="{{surgeryName}}" placeholder="请输入手术名称" />\n    <view class="label">手术时间</view>\n    <input model:value="{{surgeryTime}}" placeholder="例如 2026-05-20" />\n    <button type="primary" bindtap="submit" class="btn">提交</button>\n  </view>\n</view>');

write("pages/staff-followup-tasks/staff-followup-tasks.js", 'const api = require("../../utils/api");\nPage({\n  data: { tasks: [], status: "" },\n  async onLoad() { this.load(); },\n  async load() {\n    try {\n      const res = await api.getFollowupTasks({ status: this.data.status });\n      this.setData({ tasks: res.list });\n    } catch(e) { console.error(e); }\n  },\n  switchStatus(e) {\n    this.setData({ status: e.currentTarget.dataset.status });\n    this.load();\n  },\n  async markDone(e) {\n    const id = e.currentTarget.dataset.id;\n    try {\n      await api.updateTaskStatus(id, { status: "done" });\n      wx.showToast({ title: "已标记完成" });\n      this.load();\n    } catch(e) { wx.showToast({ title: "操作失败", icon: "none" }); }\n  },\n});');
write("pages/staff-followup-tasks/staff-followup-tasks.wxml", '<view class="container">\n  <view class="title">随访任务</view>\n  <view style="margin-bottom:12px">\n    <button size="mini" bindtap="switchStatus" data-status="">全部</button>\n    <button size="mini" bindtap="switchStatus" data-status="pending">待处理</button>\n    <button size="mini" bindtap="switchStatus" data-status="done">已完成</button>\n    <button size="mini" bindtap="switchStatus" data-status="overdue">已逾期</button>\n  </view>\n  <view wx:for="{{tasks}}" wx:key="id" class="card">\n    <view>{{item.title}}</view>\n    <view class="label">患者: {{item.patient.name}}</view>\n    <view class="label">截止日期: {{item.dueDate}}</view>\n    <view class="label" style="color:{{item.status===\'overdue\'?\'red\':\'#666\'}}">状态: {{item.status}}</view>\n    <button wx:if="{{item.status!==\'done\'}}" size="mini" type="primary" data-id="{{item.id}}" bindtap="markDone">标记完成</button>\n  </view>\n</view>');

console.log("miniprogram files created");
